# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: hrutikmehta
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: ai-app-backend
service: ai-app-backend
plugins: -serverless-plugin-typescript

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  stackName: ai-app-backend
  region: us-east-1
  versionFunctions: false
  deploymentBucket: my-ai-app-backend
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
functions:
  callchatgpt:
    handler: handler.main
    url: true
    timeout: 120
    events:
      - http:
          path: my-endpoint
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent